CREATE TABLE `users` (
  `u_id` int(222) NOT NULL,
  `username` varchar(222) NOT NULL,
  `firstname` varchar(222) NOT NULL,
  `lastname` varchar(222) NOT NULL,
  `email` varchar(222) NOT NULL,
  `phonenumber` varchar(222) NOT NULL,
  `password` varchar(222) NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=latin1;